export interface PortfolioItem {
  id: number
  src: string
  alt: string
  title: string
  category: string
  width: number
  height: number
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    src: '/images/portfolio-gallery/portfolio-01.webp',
    alt: 'Точка света',
    title: 'Точка света',
    category: 'Архитектура',
    width: 4284,
    height: 5008,
  },
  {
    id: 2,
    src: '/images/portfolio-gallery/portfolio-02.webp',
    alt: 'Глаз',
    title: 'Глаз',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 3,
    src: '/images/portfolio-gallery/portfolio-03.webp',
    alt: 'Половина света',
    title: 'Половина света',
    category: 'Портрет',
    width: 890,
    height: 1155,
  },
  {
    id: 4,
    src: '/images/portfolio-gallery/portfolio-04.webp',
    alt: 'Отлив',
    title: 'Отлив',
    category: 'Пейзаж',
    width: 3024,
    height: 4032,
  },
  {
    id: 5,
    src: '/images/portfolio-gallery/portfolio-05.webp',
    alt: 'Диалог',
    title: 'Диалог',
    category: 'Портрет',
    width: 1693,
    height: 2083,
  },
  {
    id: 6,
    src: '/images/portfolio-gallery/portfolio-06.webp',
    alt: 'Дом',
    title: 'Дом',
    category: 'Сцена',
    width: 2190,
    height: 1554,
  },
  {
    id: 7,
    src: '/images/portfolio-gallery/portfolio-07.webp',
    alt: 'Маска',
    title: 'Маска',
    category: 'Арт',
    width: 3024,
    height: 4032,
  },
  {
    id: 8,
    src: '/images/portfolio-gallery/portfolio-08.webp',
    alt: 'Белая комната',
    title: 'Белая комната',
    category: 'Портрет',
    width: 2297,
    height: 1459,
  },
  {
    id: 9,
    src: '/images/portfolio-gallery/portfolio-09.webp',
    alt: 'Туман',
    title: 'Туман',
    category: 'Архитектура',
    width: 2748,
    height: 3378,
  },
  {
    id: 10,
    src: '/images/portfolio-gallery/portfolio-10.webp',
    alt: 'Мой крест',
    title: 'Мой крест',
    category: 'Натюрморт',
    width: 3024,
    height: 4032,
  },
  {
    id: 11,
    src: '/images/portfolio-gallery/portfolio-11.webp',
    alt: 'Огни',
    title: 'Огни',
    category: 'Ночь',
    width: 3024,
    height: 4032,
  },
  {
    id: 12,
    src: '/images/portfolio-gallery/portfolio-12.webp',
    alt: 'Высота',
    title: 'Высота',
    category: 'Пейзаж',
    width: 4032,
    height: 3024,
  },
  {
    id: 13,
    src: '/images/portfolio-gallery/portfolio-13.webp',
    alt: 'Паркинг',
    title: 'Паркинг',
    category: 'Сцена',
    width: 4032,
    height: 3024,
  },
  {
    id: 14,
    src: '/images/portfolio-gallery/portfolio-14.webp',
    alt: 'Волна',
    title: 'Волна',
    category: 'Движение',
    width: 2937,
    height: 3756,
  },
  {
    id: 15,
    src: '/images/portfolio-gallery/portfolio-15.webp',
    alt: 'Падение',
    title: 'Падение',
    category: 'Движение',
    width: 4078,
    height: 4111,
  },
  {
    id: 16,
    src: '/images/portfolio-gallery/portfolio-16.webp',
    alt: 'Баланс',
    title: 'Баланс',
    category: 'Движение',
    width: 2001,
    height: 3141,
  },
  {
    id: 17,
    src: '/images/portfolio-gallery/portfolio-17.webp',
    alt: 'Роща',
    title: 'Роща',
    category: 'Пейзаж',
    width: 3024,
    height: 4032,
  },
  {
    id: 18,
    src: '/images/portfolio-gallery/portfolio-18.webp',
    alt: 'Жар',
    title: 'Жар',
    category: 'Арт',
    width: 2744,
    height: 3662,
  },
  {
    id: 19,
    src: '/images/portfolio-gallery/portfolio-19.webp',
    alt: 'Связь',
    title: 'Связь',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 20,
    src: '/images/portfolio-gallery/portfolio-20.webp',
    alt: 'Опора',
    title: 'Опора',
    category: 'Архитектура',
    width: 1733,
    height: 3415,
  },
  {
    id: 21,
    src: '/images/portfolio-gallery/portfolio-21.webp',
    alt: 'Ожидание',
    title: 'Ожидание',
    category: 'Интерьер',
    width: 4058,
    height: 4939,
  },
  {
    id: 22,
    src: '/images/portfolio-gallery/portfolio-22.webp',
    alt: 'Стоянка',
    title: 'Стоянка',
    category: 'Сцена',
    width: 2748,
    height: 2966,
  },
  {
    id: 23,
    src: '/images/portfolio-gallery/portfolio-23.webp',
    alt: 'Окно',
    title: 'Окно',
    category: 'Интерьер',
    width: 4284,
    height: 5712,
  },
  {
    id: 24,
    src: '/images/portfolio-gallery/portfolio-24.webp',
    alt: 'Детство',
    title: 'Детство',
    category: 'Портрет',
    width: 2850,
    height: 4032,
  },
  {
    id: 25,
    src: '/images/portfolio-gallery/portfolio-25.webp',
    alt: 'Ладонь',
    title: 'Ладонь',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 26,
    src: '/images/portfolio-gallery/portfolio-26.webp',
    alt: 'Снег',
    title: 'Снег',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 27,
    src: '/images/portfolio-gallery/portfolio-27.webp',
    alt: 'Красная маска',
    title: 'Красная маска',
    category: 'Арт',
    width: 2945,
    height: 3285,
  },
  {
    id: 28,
    src: '/images/portfolio-gallery/portfolio-28.webp',
    alt: 'Проспект',
    title: 'Проспект',
    category: 'Город',
    width: 4032,
    height: 3024,
  },
  {
    id: 29,
    src: '/images/portfolio-gallery/portfolio-29.webp',
    alt: 'Перчатки',
    title: 'Перчатки',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 30,
    src: '/images/portfolio-gallery/portfolio-30.webp',
    alt: 'Ткань',
    title: 'Ткань',
    category: 'Портрет',
    width: 2776,
    height: 2897,
  },
  {
    id: 31,
    src: '/images/portfolio-gallery/portfolio-31.webp',
    alt: 'Белое поле',
    title: 'Белое поле',
    category: 'Пейзаж',
    width: 4032,
    height: 3024,
  },
  {
    id: 32,
    src: '/images/portfolio-gallery/portfolio-32.webp',
    alt: 'Кепка',
    title: 'Кепка',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 33,
    src: '/images/portfolio-gallery/portfolio-33.webp',
    alt: 'Капюшон',
    title: 'Капюшон',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 34,
    src: '/images/portfolio-gallery/portfolio-34.webp',
    alt: 'Скамья',
    title: 'Скамья',
    category: 'Пейзаж',
    width: 4032,
    height: 3024,
  },
  {
    id: 35,
    src: '/images/portfolio-gallery/portfolio-35.webp',
    alt: 'Берег',
    title: 'Берег',
    category: 'Город',
    width: 3024,
    height: 2727,
  },
  {
    id: 36,
    src: '/images/portfolio-gallery/portfolio-36.webp',
    alt: 'Равновесие',
    title: 'Равновесие',
    category: 'Сцена',
    width: 2343,
    height: 2748,
  },
  {
    id: 37,
    src: '/images/portfolio-gallery/portfolio-37.webp',
    alt: 'Переход',
    title: 'Переход',
    category: 'Движение',
    width: 2764,
    height: 3685,
  },
  {
    id: 38,
    src: '/images/portfolio-gallery/portfolio-38.webp',
    alt: 'Молчание',
    title: 'Молчание',
    category: 'Арт',
    width: 3024,
    height: 4032,
  },
  {
    id: 39,
    src: '/images/portfolio-gallery/portfolio-39.webp',
    alt: 'Взгляд',
    title: 'Взгляд',
    category: 'Портрет',
    width: 3024,
    height: 4032,
  },
  {
    id: 40,
    src: '/images/portfolio-gallery/portfolio-40.webp',
    alt: 'Розовый круг',
    title: 'Розовый круг',
    category: 'Портрет',
    width: 3024,
    height: 3497,
  },
  {
    id: 41,
    src: '/images/portfolio-gallery/portfolio-41.webp',
    alt: 'Поворот',
    title: 'Поворот',
    category: 'Портрет',
    width: 2755,
    height: 3505,
  },
  {
    id: 42,
    src: '/images/portfolio-gallery/portfolio-42.webp',
    alt: 'Просёлок',
    title: 'Просёлок',
    category: 'Пейзаж',
    width: 3024,
    height: 4032,
  },
  {
    id: 43,
    src: '/images/portfolio-gallery/portfolio-43.webp',
    alt: 'Трасса',
    title: 'Трасса',
    category: 'Дорога',
    width: 2278,
    height: 3447,
  },
  {
    id: 44,
    src: '/images/portfolio-gallery/portfolio-44.webp',
    alt: 'Горечь',
    title: 'Горечь',
    category: 'Деталь',
    width: 3024,
    height: 4032,
  },
]
